"""Simple Windows installer GUI for configuring and installing the TallyBackupAgent service.

This script is intended to be bundled with PyInstaller into an EXE. It writes configuration
to ProgramData\TallyBackupAgent\config.json and can register/unregister the Windows service
using `sc` commands.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
import tkinter as tk
from tkinter import messagebox, filedialog

APP_NAME = "TallyBackupAgent"


def get_programdata_dir() -> Path:
    return Path(os.environ.get("PROGRAMDATA", r"C:\\ProgramData")) / APP_NAME


def write_config(cfg: dict):
    d = get_programdata_dir()
    d.mkdir(parents=True, exist_ok=True)
    cfgf = d / "config.json"
    cfgf.write_text(json.dumps(cfg, indent=2), encoding="utf-8")


def create_service(exe_path: str, args: str):
    # Use sc to create service; requires admin
    # sc expects the binPath argument in a single token. Use a quoted string.
    cmd = f'sc create {APP_NAME} binPath= "{exe_path} {args}" start= auto'
    subprocess.run(cmd, check=True, shell=True)


def delete_service():
    subprocess.run(["sc", "stop", APP_NAME], check=False)
    subprocess.run(["sc", "delete", APP_NAME], check=False)


class InstallerGUI:
    def __init__(self, root):
        self.root = root
        root.title("TallyPrime Backup Agent - Installer")

        tk.Label(root, text="S3 Bucket").grid(row=0, column=0, sticky="e")
        self.bucket = tk.Entry(root, width=40)
        self.bucket.grid(row=0, column=1)

        tk.Label(root, text="Client ID").grid(row=1, column=0, sticky="e")
        self.client = tk.Entry(root, width=40)
        self.client.grid(row=1, column=1)

        tk.Label(root, text="Encryption Password").grid(row=2, column=0, sticky="e")
        self.password = tk.Entry(root, width=40, show="*")
        self.password.grid(row=2, column=1)

        tk.Label(root, text="Debounce (seconds)").grid(row=3, column=0, sticky="e")
        self.debounce = tk.Entry(root, width=10)
        self.debounce.insert(0, "120")
        self.debounce.grid(row=3, column=1, sticky="w")

        tk.Label(root, text="AWS Region").grid(row=4, column=0, sticky="e")
        self.region = tk.Entry(root, width=20)
        self.region.grid(row=4, column=1, sticky="w")

        tk.Label(root, text="Agent EXE").grid(row=5, column=0, sticky="e")
        self.exe_path = tk.Entry(root, width=40)
        self.exe_path.grid(row=5, column=1, sticky="w")
        tk.Button(root, text="Browse", command=self.browse_exe).grid(row=5, column=2)

        tk.Button(root, text="Install Service", command=self.install).grid(row=6, column=0)
        tk.Button(root, text="Uninstall Service", command=self.uninstall).grid(row=6, column=1)
        tk.Button(root, text="Save Config Only", command=self.save_config).grid(row=6, column=2)

    def browse_exe(self):
        p = filedialog.askopenfilename(title="Select Agent EXE", filetypes=[("Executables", "*.exe"), ("All files", "*")])
        if p:
            self.exe_path.delete(0, tk.END)
            self.exe_path.insert(0, p)

    def save_config(self):
        cfg = {
            "s3_bucket": self.bucket.get().strip(),
            "client_id": self.client.get().strip(),
            "encryption_password": self.password.get().strip(),
            "debounce_seconds": int(self.debounce.get().strip() or 120),
            "aws_region": self.region.get().strip() or None,
        }
        write_config(cfg)
        messagebox.showinfo("Saved", f"Configuration saved to {get_programdata_dir()}")

    def install(self):
        exe = self.exe_path.get().strip()
        if not exe:
            messagebox.showerror("Error", "Please select the agent EXE generated by PyInstaller.")
            return

        self.save_config()
        # Build args (service wrapper will read config)
        args = ""
        try:
            create_service(exe, args)
            # Attempt to start the service immediately
            try:
                subprocess.run(["sc", "start", APP_NAME], check=False)
            except Exception:
                # Best-effort; continue even if start fails
                pass
            messagebox.showinfo("Success", "Service created and start requested. Verify in Services.msc.")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to create service: {e}")

    def uninstall(self):
        try:
            delete_service()
            messagebox.showinfo("Success", "Service removed.")
        except Exception as e:
            messagebox.showerror("Error", f"Failed to remove service: {e}")


def main():
    root = tk.Tk()
    InstallerGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
